version: '3'

services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: danielmarini/fullcycle-desafio-docker-01:latest
    entrypoint: /app/app
    container_name: app
    networks: 
      - golang-network

networks: 
  golang-network:
    driver: bridge      
